server:
  port: 9001
spring:
  application:
    name: search
  data:
    elasticsearch:
      cluster-nodes: 10.0.0.19:9300
# 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goods?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update  # 第一次简表create  后面用update
    show-sql: true
  redis:
    host: localhost
    password: 123456

hbase.zookeeper.quorum: wx,twl
hbase.zookeeper.port: 2181

mykafka:
  producter:
    nodes: localhost:9092
    retries: 0
    batchSize: 4096
    lingerMs: 1
    bufferMemory: 40960
  consumer:
    bootstrapServers: localhost:9092
    enableAutoCommit: false
    autoCommitIntervalMs: 100
    sessionTimeoutMs: 15000
    groupId: test_group
    autoOffsetReset: latest


my-page:
  page: 1
  size: 10


